### ISSUE TITLE
The pseudo_labels might be discontinuous

### ISSUE THREAD

**Issue by iChenning** [yxgeee/SpCL#21]
Thanks for your great sharing. When I‘m debugging the code, I found that the pseudo_labels might be discontinuous. 
If I let:
len_ = len(set(pseudo_labels.numpy().tolist()))
min_ = min(set(pseudo_labels.numpy().tolist()))
max_ = max(set(pseudo_labels.numpy().tolist()))
sametimes max_ not equal to the (min_ + len_ - 1).

Thanks again for sharing. It would be perfect if you could solve this.

**Comment by yxgeee** [comment]
Hi, thanks for this report. I did not notice it before. But it would not affect the final results, since we use non-parametric memory module with centroids instead of a learnable classifier. For example, if a class ID of 5 does not exist, re-labeling the clusters or using the discontinuous ones would result in the same training objective in our SpCL pipeline. However, in general clustering-based training, the classifier would be affected since the class weight of no. 5 always cannot be optimized.
