### ISSUE TITLE
Impact of Domain Specific BN and RandomMultipleGallerySampler

### ISSUE THREAD

**Issue by Xiangyu-CAS** [yxgeee/SpCL#3]
Hi, I am wondering how much Domain Specific BN and RandomMultipleGallerySampler contribute to the final result? As you mentioned DSBN is crucial in OpenUnReID, but I didn't find a fair comparison in papers.

On the other hand, I noticed you ranked 1st in Visda 2020 challenge now, which proves your method is superior in Domain Adaptation.  Is SpCl your baseline method used in Visda challenge?  

Thank you!

**Comment by yxgeee** [comment]
Hi,

1. DSBN is mainly adopted for training domain adaptive models in only one stage without extra effort on source-domain pretraining. DSBN benefits the model properly due to the extended classes and training data, i.e. source+target. The performance will be hurt if you jointly train different domains' images with the same BNs.
2. I haven't compared the performance between RandomMultipleGallerySampler and conventional IdentitySampler. I don't think it is critical to performance.
3. Thanks for your interest. We will add the technical details of the method for VisDA2020 in OpenUnReID after the deadline of the competition.

**Comment by yxgeee** [comment]
Plus, DSBN benefits the model properly due to the extended classes and training data, i.e. source+target.
